name: Continuous Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed
  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.action != 'closed' || github.event.pull_request.merged == true
    name: Build library
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build distributable bundles
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: parakeet.js-dist
          path: dist
          if-no-files-found: error
